//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/LadybugInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @LadybugInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @LadybugInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""LadybugInput"",
    ""maps"": [
        {
            ""name"": ""LadybugMove"",
            ""id"": ""cf25782c-c548-4d7f-954c-29c558acbc93"",
            ""actions"": [
                {
                    ""name"": ""MoveForward"",
                    ""type"": ""Button"",
                    ""id"": ""04cbcace-76f0-4093-b20b-4e112f54f4ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""bee166a5-f710-4b3a-9f77-cd4b35e9ebd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""6221dc40-f21d-4c6e-b8ab-f532481de578"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveBack"",
                    ""type"": ""Button"",
                    ""id"": ""42f70d9a-e5e0-40a0-a6ab-0350add9fd40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""215466bc-04ea-4833-ab48-89cbcad71fc2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7758ab14-cde0-4a82-be0f-9d30af6cf8be"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77e7ca82-be9b-4cc7-b911-3d4063c8c6a9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9994035-5e0b-4eca-9b63-0f59c11834a5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c72112ea-49f0-4654-b7b1-53ea03776b15"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40d8b3da-3f02-4015-b72e-aafef7eeb312"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b8be083-abd0-4ff8-b1e5-9dcef327b85f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a36ed229-14d4-4d59-9ff5-41858370f182"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LadybugMove
        m_LadybugMove = asset.FindActionMap("LadybugMove", throwIfNotFound: true);
        m_LadybugMove_MoveForward = m_LadybugMove.FindAction("MoveForward", throwIfNotFound: true);
        m_LadybugMove_MoveLeft = m_LadybugMove.FindAction("MoveLeft", throwIfNotFound: true);
        m_LadybugMove_MoveRight = m_LadybugMove.FindAction("MoveRight", throwIfNotFound: true);
        m_LadybugMove_MoveBack = m_LadybugMove.FindAction("MoveBack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LadybugMove
    private readonly InputActionMap m_LadybugMove;
    private ILadybugMoveActions m_LadybugMoveActionsCallbackInterface;
    private readonly InputAction m_LadybugMove_MoveForward;
    private readonly InputAction m_LadybugMove_MoveLeft;
    private readonly InputAction m_LadybugMove_MoveRight;
    private readonly InputAction m_LadybugMove_MoveBack;
    public struct LadybugMoveActions
    {
        private @LadybugInput m_Wrapper;
        public LadybugMoveActions(@LadybugInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveForward => m_Wrapper.m_LadybugMove_MoveForward;
        public InputAction @MoveLeft => m_Wrapper.m_LadybugMove_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_LadybugMove_MoveRight;
        public InputAction @MoveBack => m_Wrapper.m_LadybugMove_MoveBack;
        public InputActionMap Get() { return m_Wrapper.m_LadybugMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LadybugMoveActions set) { return set.Get(); }
        public void SetCallbacks(ILadybugMoveActions instance)
        {
            if (m_Wrapper.m_LadybugMoveActionsCallbackInterface != null)
            {
                @MoveForward.started -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveForward;
                @MoveForward.performed -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveForward;
                @MoveForward.canceled -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveForward;
                @MoveLeft.started -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveRight;
                @MoveBack.started -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveBack;
                @MoveBack.performed -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveBack;
                @MoveBack.canceled -= m_Wrapper.m_LadybugMoveActionsCallbackInterface.OnMoveBack;
            }
            m_Wrapper.m_LadybugMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveForward.started += instance.OnMoveForward;
                @MoveForward.performed += instance.OnMoveForward;
                @MoveForward.canceled += instance.OnMoveForward;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @MoveBack.started += instance.OnMoveBack;
                @MoveBack.performed += instance.OnMoveBack;
                @MoveBack.canceled += instance.OnMoveBack;
            }
        }
    }
    public LadybugMoveActions @LadybugMove => new LadybugMoveActions(this);
    public interface ILadybugMoveActions
    {
        void OnMoveForward(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnMoveBack(InputAction.CallbackContext context);
    }
}
